---
- name: Tasks for "centos" hosts
  hosts: centos
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - influxdata.chrony
    - geerlingguy.repo-epel
    - linuxhq.yum-cron
    - hxr.admin-tools
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
