---
- name: galaxy
  hosts: galaxy
  become: true
  become_user: galaxy
  #vars_files:
    #- "secret_group_vars/all.yml"
    #- [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - hxr.galaxy-echo-tool
