---
- name: Tasks for "grafana" hosts
  hosts: grafana
  become: true
#  vars_files:
#    - "secret_group_vars/pgs.yml"
#    - "secret_group_vars/grafana.yml"
#    - "secret_group_vars/all.yml"
#    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  vars:
    hostname: stats.genome.edu.au
  roles:
    - hostname
    - hxr.certbot
    - hxr.admin-tools
    - geerlingguy.nginx
    #- hxr.simple-nagios
    - picotrading.ansible-grafana
    #- pgs
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - jnv.unattended-upgrades
