---
- name: Tasks for "grafana" hosts
  hosts: grafana
  become: true
  vars_files:
    #- "secret_group_vars/pgs.yml"
    - "secret_group_vars/grafana.yml"
    #- "secret_group_vars/all.yml"
    #- [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  vars:
    hostname: stats.genome.edu.au
  roles:
#    - hostname
#    - influxdata.chrony
#    - hxr.certbot
#    - hxr.admin-tools
#    - geerlingguy.nginx
#    - dj-wasabi.telegraf
    - hxr.simple-nagios
#    - picotrading.ansible-grafana
#    - mtchavez.influxdb
    #- pgs
    #- dev-sec.os-hardening
    #- dev-sec.ssh-hardening
