---
- name: test.usegalaxy.eu
  hosts: usegalaxy-test
  become: true
  vars:
    hostname: test.usegalaxy.eu
  vars_files:
    - "group_vars/usegalaxy-test.yml"
    - "secret_group_vars/all.yml"
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  roles:
    - hostname
    - geerlingguy.repo-epel
    - influxdata.chrony
    - hxr.certbot
    - hxr.admin-tools
    - linuxhq.yum-cron
    - hxr.autofs
    - geerlingguy.nginx
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - multinic
